# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_transfer.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "filetransfer.FileRequest" do
    optional :name, :string, 1
    optional :content, :string, 2
    optional :size, :int64, 3
  end
  add_message "filetransfer.FileResponse" do
    optional :name, :string, 1
    optional :content, :string, 2
  end
end

module Filetransfer
  FileRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("filetransfer.FileRequest").msgclass
  FileResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("filetransfer.FileResponse").msgclass
end
