# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: file_transfer.proto for package 'filetransfer'

require 'grpc'
require_relative 'file_transfer_pb'

module Filetransfer
  module FileTransfer
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'filetransfer.FileTransfer'

      rpc :TransferFile, ::Filetransfer::FileRequest, ::Filetransfer::FileResponse
    end

    Stub = Service.rpc_stub_class
  end
end
